### ISSUE TITLE
IntegrityError if you try to create two records with the same last_modified value in a batch

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto#1569]
```
demo:
  collections:
    demo:
      records:
        abc:
          data:
            last_modified: 123
        efg:
          data:
            last_modified: 123
```

```
$ kinto-wizard load -s https://kinto.dev.mozaws.net/v1 -a admin:admin  demo.yaml --force -b demo -c demo
kinto_http.exceptions.KintoException: POST /v1/batch - 503 503 - 
{'message': 'Service temporary unavailable due to overloading or maintenance, please retry later.',
 'code': 503, 'errno': 201, 'error': 'Service Unavailable'}
```

**Comment by leplatrem** [comment]
Nice catch :)

**Comment by atulpillai** [comment]
Hi Guys, new here. I was trying to reproduce the issue on my local but no luck:
Please check below, I might be missing something....

`kinto-wizard load -s http://localhost:8888/v1 -a admin:admin demo.yaml --force -b demo -c demo`

```
demo:
  collections:
     demo:
        records:
           abcd:
              data:
               last_modified: 123

           efgh:
              data:
               last_modified: 123
```
```
$ kinto-wizard load -s http://localhost:8888/v1 -a admin:admin demo.yaml --force -b demo -c demo
Batch #0: PUT /buckets/demo - 200 
Batch #1: PUT /buckets/demo/collections/demo - 200 
Batch #2: PUT /buckets/demo/collections/demo/records/abcd - 201 
Batch #3: PUT /buckets/demo/collections/demo/records/efgh - 201 
```

```
$ http GET http://localhost:8888/v1/buckets/demo/collections/demo/records -a admin:admin
HTTP/1.1 200 OK
Access-Control-Expose-Headers: Cache-Control, Total-Records, Retry-After, Backoff, Alert, ETag, Pragma, Next-Page, Expires, Content-Length, Last-Modified
Cache-Control: no-cache, no-store
Content-Length: 164
Content-Type: application/json
Date: Thu, 19 Apr 2018 19:41:51 GMT
Etag: "1524166341794"
Last-Modified: Thu, 19 Apr 2018 19:32:21 GMT
Server: waitress
Total-Records: 4
X-Content-Type-Options: nosniff

{
    "data": [
        {
            "id": "efg",
            "last_modified": 1524166341794
        },
        {
            "id": "abc",
            "last_modified": 1524166341791
        },
        {
            "id": "abcd",
            "last_modified": 123
        },
        {
            "id": "efgh",
            "last_modified": 123
        }
    ]
}
```
