### ISSUE TITLE
Kinto onboarding experience (part 1)

### ISSUE THREAD

**Issue by n1k0** [Kinto/kinto#1733]
These is random feedback with onboarding when setting up Kinto using docker-compose following the official docs at http://docs.kinto-storage.org/en/stable/tutorials/install.html#using-docker-compose.

You may want to spawn several issues out of all this, your call.

```
$ docker --version
Docker version 18.06.0-ce, build 0ffa825
$ docker-compose --version
docker-compose version 1.18.0, build 8dd22a9
$ wget https://raw.githubusercontent.com/Kinto/kinto/master/docker-compose.yml
$ docker-compose up
```

> Note I don't use sudo as it's not mandatory using docker when properly configured.

To retrieve the `kinto.ini` configuration file, I'm doing:

```
$ mkdir config
$ docker-compose exec web cat /etc/kinto/kinto.ini > config/kinto.ini
```

I enabled the admin by updating the related section:

```
kinto.includes = kinto.plugins.default_bucket
                 kinto.plugins.admin
```

And updated the `docker-compose.yml` file to mount config to a local volume:

```
db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
cache:
  image: library/memcached
web:
  image: kinto/kinto-server
  links:
  - db
  - cache
  ports:
  - "8888:8888"
  volumes:
  - ./config:/etc/kinto
  environment:
    KINTO_CACHE_BACKEND: kinto.core.cache.memcached
    KINTO_CACHE_HOSTS: cache:11211 cache:11212
    KINTO_STORAGE_BACKEND: kinto.core.storage.postgresql
    KINTO_STORAGE_URL: postgres://postgres:postgres@db/postgres
    KINTO_PERMISSION_BACKEND: kinto.core.permission.postgresql
    KINTO_PERMISSION_URL: postgres://postgres:postgres@db/postgres
```

Then restarted the server.

The root endpoint loads fine at `http://127.0.0.1:8888`, thoug I noticed errors in the docker console:

```
web_1    | "GET   /?" 307 (3 ms)  agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 errno=0 lang=fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7 time=2018-08-14T12:10:26.610000
web_1    | Created new connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> 
web_1    | Created new connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> checked out from pool 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> checked out from pool 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> being returned to pool 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> being returned to pool 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> rollback-on-return, via agent 
web_1    | Connection <connection object at 0x7fa1383f22a8; dsn: 'user=postgres password=xxx dbname=postgres host=db', closed: 0> rollback-on-return, via agent 
```

Though the admin loads fine at `http://127.0.0.1:8888/admin`, and I'm presented with a login form. I chose `Basic Auth`, entered test:test. This is the UI I'm facing right now:

![](https://i.imgur.com/LcmZC7Y.png)

Notice that even though the `default_bucket` plugin is enabled in my configuration, I can't see it listed in the sidebar.

**But** there's a `bucket` bucket listed in the sidebar. When inspecting its properties by clicking on the gear icon next to it, I see this:

![](https://i.imgur.com/jZ2da6v.png)

Neither I can't list its collections:

![](https://i.imgur.com/5wBbpMZ.png)

BTW the docker logs have this strange line, probably related:

```
web_1    | Permission 'read' on '/buckets/undefined' not granted to 'basicauth:fc14066cad43629ec6d2e4b6514ce715d3fe7f587763bb7cf0cdc77645cc958e'. perm=read uri=/buckets/undefined userid=basicauth:fc14066cad43629ec6d2e4b6514ce715d3fe7f587763bb7cf0cdc77645cc958e
```

So while this bucket might have a reason to exist technically, from a UX perspective it's really intriguing adn confusing; why is it here? What is it useful for? Why can't I do anything with it? Or could this be a bug where this strange *undefined* bucket is the default bucket mishandled? Mysteries.

Now on the other hand, I can create a new bucket just fine, and collections in it.

Now I click the Logout button. I'm now facing this screen:

![](https://i.imgur.com/aO30fmL.png)

The login form is gone. Clicking the "sign in" button brings this new error:

![](https://i.imgur.com/8kZEcxZ.png)

From there, I have no other option to reload the page. It seems like a kinto-admin issue, with a lot of cryptic js errors in the console:

![](https://i.imgur.com/0MD5geF.png)

So this was my initial onboarding experience with the project after a year being away from it. While I've been able to eventually make it work, it wasn't a smooth experience, and my impression was that the whole product is somewhat fragile, at the very least from a UX perspective with the admin.

After that I enabled the account plugin, which brought other issues I'm gonna file in another ticket.
